package br.com.imobmatch.api.models.phone;

import br.com.imobmatch.api.models.user.User;
import jakarta.persistence.*;
import lombok.*;

import java.util.UUID;

/**
 * <p>
 *   embeddable phone structure for Owners and Broker<br>
 *   To use it, declare a field with the type "Phone" and place the @Embedded annotation on it.
 * </p>
 *
 *
 * <p>JPA will recognize the field as an @Embeddable and will incorporate it into the entity.</p>
 *
 * <p>In the table, this entity will gain 2 fields: phone_number and phone_ddd
 * when it is generated by JPA.</p>
 *
 * <p>ATTENTION: You need to update your migration to reflect this new table.
 * If you generate the database with ddl-auto=update, JPA will generate it automatically.</p>
 *
 * <p>ATTENTION TO THE FIELD DECLARATION: The generated columns accept NULL and NOT UNIQUE values.
 * In this new version, there may be repeated phone numbers in the database.
 * It also considers that phone number can be an optional value.
 * That is, it can be added or removed.</p>
 *
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class Phone {

    @Column(name = "phone_ddd", length = 3)
    private String ddd;

    @Column(name = "phone_number", length = 20)
    private String number;

    public String getFormatedNumber(){

        return "(" + ddd + ") " + number;
    }
}
